from __future__ import annotations


_SMART_ALERT_PANEL = '''<section class="panel"><h2>Smart signal alerts</h2><p class="muted">Notify while PrediBeacon is open when a followed market enters a new observable signal state. Missing data never triggers an alert.</p><div class="smart-options"><label><input id="smart-breaking" type="checkbox" checked> Breaking move</label><label><input id="smart-execution" type="checkbox" checked> Weak execution quality</label><label><input id="smart-large" type="checkbox" checked> New large-trade activity</label><label><input id="smart-gap" type="checkbox" checked> Verified disagreement ≥ 5 pts</label></div><button class="button" id="add-smart" type="button">Save signal alerts</button><p id="smart-message" class="muted"></p><div id="smart-alerts"></div><p class="muted">Signal alerts are local browser preferences and are checked every five minutes while this page is open. They are not forecasts or trading recommendations.</p></section>'''

_SMART_ALERT_STYLE = '''.smart-options{display:grid;grid-template-columns:repeat(2,1fr);gap:.65rem;margin:.8rem 0 1rem}.smart-options label{border:1px solid var(--line);border-radius:10px;padding:.75rem;background:var(--bg)}@media(max-width:650px){.smart-options{grid-template-columns:1fr}}'''

_SMART_ALERT_SCRIPT = r'''
const smartKey='predibeacon-smart-alerts',smartBox=document.querySelector('#smart-alerts'),smartMessage=document.querySelector('#smart-message');
function smartList(){try{return JSON.parse(localStorage.getItem(smartKey)||'[]')}catch{return[]}}
function smartSave(items){localStorage.setItem(smartKey,JSON.stringify(items));renderSmart()}
async function smartSnapshot(marketId){try{const r=await fetch('/api/v1/market/alert-signals?'+new URLSearchParams({market_id:marketId}));return r.ok?await r.json():null}catch{return null}}
function smartState(snapshot){return{breaking:!!(snapshot?.breaking?.available&&snapshot.breaking.active),execution:!!(snapshot?.execution?.available&&snapshot.execution.score!=null&&snapshot.execution.score<=45),largeKey:snapshot?.large_trade_activity?.available?snapshot.large_trade_activity.latest_signal_key:null,gap:!!(snapshot?.cross_platform?.equivalent_contracts&&snapshot.cross_platform.gap_points!=null&&snapshot.cross_platform.gap_points>=5)}}
function smartNotify(title,body){if('Notification'in window&&Notification.permission==='granted')new Notification(title,{body})}
async function addSmart(){const marketId=marketSelect.value;if(!marketId){smartMessage.textContent='Choose a market first.';return}const enabled={breaking:document.querySelector('#smart-breaking').checked,execution:document.querySelector('#smart-execution').checked,large:document.querySelector('#smart-large').checked,gap:document.querySelector('#smart-gap').checked};if(!Object.values(enabled).some(Boolean)){smartMessage.textContent='Choose at least one signal type.';return}if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();const snapshot=await smartSnapshot(marketId);if(!snapshot){smartMessage.textContent='Signal data is temporarily unavailable. Nothing was saved.';return}const current=smartState(snapshot),items=smartList().filter(item=>item.market_id!==marketId);items.push({market_id:marketId,enabled,last:current});smartSave(items);const m=await market(marketId);smartMessage.textContent='Smart signal alerts saved for '+(m?.title||'this market')+'.'}
async function renderSmart(){const items=smartList();if(!items.length){smartBox.innerHTML='<div class="empty muted">No smart signal alerts saved yet.</div>';return}const rows=[];for(const item of items){const m=await market(item.market_id),types=[];if(item.enabled?.breaking)types.push('Breaking');if(item.enabled?.execution)types.push('Execution');if(item.enabled?.large)types.push('Large trade');if(item.enabled?.gap)types.push('Verified gap');rows.push(`<div class="alert"><span><strong>${esc(m?.title||'Market no longer available')}</strong><br><span class="muted">${esc(types.join(' · '))}</span><br><span class="badge">SMART SIGNALS</span></span><button class="input secondary remove-smart" data-id="${esc(item.market_id)}" type="button">Remove</button></div>`)}smartBox.innerHTML=rows.join('')}
async function checkSmart(){const items=smartList();let changed=false;for(const item of items){const snapshot=await smartSnapshot(item.market_id);if(!snapshot)continue;const next=smartState(snapshot),m=await market(item.market_id),title=m?.title||'PrediBeacon market';if(item.enabled?.breaking&&next.breaking&&!item.last?.breaking)smartNotify('PrediBeacon · Breaking move',title+' entered a fresh acceleration signal.');if(item.enabled?.execution&&next.execution&&!item.last?.execution)smartNotify('PrediBeacon · Execution quality',title+' currently has weak displayed execution quality.');if(item.enabled?.large&&next.largeKey&&next.largeKey!==item.last?.largeKey)smartNotify('PrediBeacon · Large trade activity',title+' has a new unusually large observed trade in the public sample.');if(item.enabled?.gap&&next.gap&&!item.last?.gap)smartNotify('PrediBeacon · Verified disagreement',title+' now has a verified cross-platform gap of at least 5 points.');if(JSON.stringify(item.last)!==JSON.stringify(next)){item.last=next;changed=true}}if(changed)localStorage.setItem(smartKey,JSON.stringify(items));await renderSmart()}
document.querySelector('#add-smart').addEventListener('click',addSmart);smartBox.addEventListener('click',event=>{const button=event.target.closest('.remove-smart');if(button)smartSave(smartList().filter(item=>item.market_id!==button.dataset.id))});renderSmart();checkSmart();setInterval(checkSmart,300000);
'''


def enhance_alerts_template(body: str) -> str:
    panel_anchor = '<section class="panel"><h2>Saved alerts</h2>'
    style_anchor = '</style>'
    script_anchor = "document.querySelector('#add').addEventListener('click',add);"
    if panel_anchor not in body or style_anchor not in body or script_anchor not in body:
        return body
    body = body.replace(panel_anchor, _SMART_ALERT_PANEL + panel_anchor, 1)
    body = body.replace(style_anchor, _SMART_ALERT_STYLE + style_anchor, 1)
    body = body.replace(script_anchor, _SMART_ALERT_SCRIPT + script_anchor, 1)
    return body
