from __future__ import annotations


_EXECUTION_PANEL = '''<section class="panel"><div class="eyebrow">EXECUTION QUALITY</div><h2>What does the visible order book look like?</h2><div id="execution-quality" class="cross" role="status" aria-live="polite"><span class="muted">Checking displayed spread and depth…</span></div><p class="notice">Execution Quality describes the currently displayed order book. It does not include every fee or trading friction and is not a fill, liquidity, profitability or best-execution guarantee.</p></section>'''

_TRADE_ACTIVITY_PANEL = '''<section class="panel"><div class="eyebrow">LARGE TRADE ACTIVITY</div><h2>Were unusually large trades observed?</h2><div id="large-trade-activity" class="cross" role="status" aria-live="polite"><span class="muted">Checking recent public trade activity…</span></div><p class="notice">Large Trade Activity is a size anomaly signal from a recent public sample. It does not identify a trader or imply insider knowledge, manipulation, profitability, causation or future direction.</p></section>'''

_VENUE_CONDITIONS_PANEL = '''<section class="panel"><div class="eyebrow">VERIFIED VENUE CONDITIONS</div><h2>How do equivalent contracts look across venues?</h2><div id="venue-conditions" class="cross" role="status" aria-live="polite"><span class="muted">Checking verified cross-platform execution conditions…</span></div><p class="notice">PrediBeacon does not label a best venue until fees, settlement differences, slippage and other trading frictions are validated. This panel compares observable conditions only.</p></section>'''

_EXECUTION_SCRIPT = r'''async function loadExecutionQuality(){const target=document.querySelector('#execution-quality');if(!target||!id)return;try{const r=await fetch('/api/v1/market/execution-quality?'+new URLSearchParams({market_id:id}));if(!r.ok)throw new Error();const d=await r.json();target.replaceChildren();if(!d.available){const message=document.createElement('span');message.className='muted';message.textContent=(d.reasons||[]).join(' · ')||'A two-sided displayed order book is not available right now.';target.append(message);return}const grade=document.createElement('strong');grade.textContent='Execution Quality '+String(d.score??'—')+'/100 · '+String(d.grade||'').toUpperCase();target.append(grade);const grid=document.createElement('div');grid.className='crossgrid';const values=[['Best bid',d.best_bid==null?'—':Math.round(d.best_bid*100)+'%'],['Best ask',d.best_ask==null?'—':Math.round(d.best_ask*100)+'%'],['Spread',d.spread_points==null?'—':Number(d.spread_points).toFixed(2)+' pts'],['Bid depth',d.bid_depth_units==null?'—':Number(d.bid_depth_units).toLocaleString('en-US')+' units'],['Ask depth',d.ask_depth_units==null?'—':Number(d.ask_depth_units).toLocaleString('en-US')+' units'],['Midpoint',d.midpoint==null?'—':Math.round(d.midpoint*100)+'%']];for(const[label,value]of values){const box=document.createElement('div'),name=document.createElement('span'),number=document.createElement('div');name.className='muted';name.textContent=label;number.className='crossvalue';number.textContent=value;box.append(name,number);grid.append(box)}target.append(grid);if(d.reasons?.length){const note=document.createElement('p');note.className='muted';note.textContent=d.reasons.join(' · ');target.append(note)}}catch{target.replaceChildren();const message=document.createElement('span');message.className='muted';message.textContent='Execution Quality is temporarily unavailable. PrediBeacon will not infer missing order-book data.';target.append(message)}}'''

_TRADE_ACTIVITY_SCRIPT = r'''async function loadLargeTradeActivity(){const target=document.querySelector('#large-trade-activity');if(!target||!id)return;try{const r=await fetch('/api/v1/market/large-trade-activity?'+new URLSearchParams({market_id:id,limit:'5'}));if(!r.ok)throw new Error();const d=await r.json();target.replaceChildren();const summary=document.createElement('strong');summary.textContent=d.sample_size?String(d.sample_size)+' recent trades sampled · '+String(d.signal_count)+' unusually large observed':'No usable recent public trade sample is available.';target.append(summary);if(!d.signals?.length){const note=document.createElement('p');note.className='muted';note.textContent=d.sample_size?'No observed trade cleared both PrediBeacon size thresholds in this sample.':'PrediBeacon will not infer large-trade activity without usable public trade data.';target.append(note);return}const list=document.createElement('div');list.className='related-list';for(const signal of d.signals){const item=document.createElement('div');item.className='timeline-item';const amount=document.createElement('strong');amount.textContent=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(signal.notional_usd)+' observed trade';const detail=document.createElement('span');detail.className='muted';const multiple=signal.multiple_of_median==null?'':(' · '+Number(signal.multiple_of_median).toFixed(1)+'× sample median');detail.textContent=new Date(signal.occurred_at).toLocaleString()+' · '+String(signal.severity).replaceAll('_',' ')+' size anomaly'+multiple;item.append(amount,document.createElement('br'),detail);list.append(item)}target.append(list);if(d.sample_median_usd!=null){const median=document.createElement('p');median.className='notice';median.textContent='Sample median observed trade value: '+new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(d.sample_median_usd)+'.';target.append(median)}}catch{target.replaceChildren();const message=document.createElement('span');message.className='muted';message.textContent='Large Trade Activity is temporarily unavailable. PrediBeacon will not manufacture a replacement signal.';target.append(message)}}'''

_VENUE_CONDITIONS_SCRIPT = r'''async function loadVenueConditions(){const target=document.querySelector('#venue-conditions');if(!target||!id)return;try{const r=await fetch('/api/v1/market/venue-conditions?'+new URLSearchParams({market_id:id}));if(!r.ok)throw new Error();const d=await r.json();target.replaceChildren();if(!d.equivalent_contracts||!d.venues?.length){const message=document.createElement('span');message.className='muted';message.textContent=(d.reasons||[]).join(' · ')||'No verified equivalent pair is available for venue-condition comparison.';target.append(message);return}const badge=document.createElement('span');badge.className='verified';badge.textContent='VERIFIED EQUIVALENT · '+String(d.verification_confidence??'—')+'/100';target.append(badge);const list=document.createElement('div');list.className='related-list';for(const venue of d.venues){const card=document.createElement('div');card.className='related';const title=document.createElement('strong');title.textContent=venue.venue==='kalshi'?'KALSHI':'POLYMARKET';const grid=document.createElement('div');grid.className='crossgrid';const values=[['Probability',venue.probability==null?'—':Math.round(venue.probability*100)+'%'],['Spread',venue.spread_points==null?'—':Number(venue.spread_points).toFixed(2)+' pts'],['Bid depth',venue.bid_depth_units==null?'—':Number(venue.bid_depth_units).toLocaleString('en-US')],['Ask depth',venue.ask_depth_units==null?'—':Number(venue.ask_depth_units).toLocaleString('en-US')],['Execution',venue.execution_score==null?'—':String(venue.execution_score)+'/100'],['Volume',venue.reported_volume_usd==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact'}).format(venue.reported_volume_usd)]];for(const[label,value]of values){const box=document.createElement('div'),name=document.createElement('span'),number=document.createElement('div');name.className='muted';name.textContent=label;number.className='crossvalue';number.textContent=value;box.append(name,number);grid.append(box)}card.append(title,grid);list.append(card)}target.append(list);const note=document.createElement('p');note.className='notice';note.textContent='No best-venue ranking: fees, settlement, slippage, fill probability and other frictions are not fully included.';target.append(note)}catch{target.replaceChildren();const message=document.createElement('span');message.className='muted';message.textContent='Verified venue conditions are temporarily unavailable. PrediBeacon will not compare unverified contracts.';target.append(message)}}'''

_CROSS_PLATFORM_V2_SCRIPT = r'''async function loadCrossPlatformV2(){if(!currentMarket)return;const target=document.querySelector('#cross-platform');try{const r=await fetch('/api/v1/market/cross-platform?'+new URLSearchParams({market_id:id,candidate_limit:'3'}));if(!r.ok)throw new Error();const d=await r.json();target.replaceChildren();if(!d.counterpart){const empty=document.createElement('span');empty.className='muted';empty.textContent='No plausible cross-platform counterpart cleared candidate discovery on the current feeds.';target.append(empty);return}const other=d.counterpart,v=d.verification;if(!v||!v.equivalent_contracts){const headline=document.createElement('strong');headline.textContent='Candidate found on '+(other.venue==='kalshi'?'Kalshi':'Polymarket')+', but equivalence is not verified.';const title=document.createElement('p');title.className='muted';title.textContent=other.title;const note=document.createElement('p');note.className='notice';note.textContent='Candidate score '+Number(d.candidate_score||0).toFixed(1)+'/115. PrediBeacon will not compute consensus or disagreement for this pair.';target.append(headline,title,note);return}const badge=document.createElement('span');badge.className='verified';badge.textContent='VERIFIED EQUIVALENT';target.append(badge);const grid=document.createElement('div');grid.className='crossgrid';const currentLabel=currentMarket.venue==='kalshi'?'Kalshi':'Polymarket',otherLabel=other.venue==='kalshi'?'Kalshi':'Polymarket';const values=[[currentLabel,currentMarket.probability==null?'—':Math.round(currentMarket.probability*100)+'%'],[otherLabel,other.probability==null?'—':Math.round(other.probability*100)+'%'],['Consensus',v.consensus_probability==null?'—':Math.round(v.consensus_probability*100)+'%']];for(const[label,value]of values){const box=document.createElement('div'),name=document.createElement('span'),number=document.createElement('div');name.className='muted';name.textContent=label;number.className='crossvalue';number.textContent=value;box.append(name,number);grid.append(box)}target.append(grid);const gap=document.createElement('p');gap.className='muted';gap.textContent=v.gap_points==null?'Comparable probability is unavailable.':Number(v.gap_points).toFixed(1)+' percentage-point verified disagreement.';const confidence=document.createElement('p');confidence.className='notice';confidence.textContent='Contract verification confidence '+String(v.confidence)+'/100. Consensus is the simple mean of verified equivalent contracts, not a statistical forecast.';target.append(gap,confidence)}catch{target.replaceChildren();const unavailable=document.createElement('span');unavailable.className='muted';unavailable.textContent='Cross-platform verification is temporarily unavailable. PrediBeacon will not substitute title-only matching.';target.append(unavailable)}}'''


def enhance_market_template(body: str) -> str:
    """Add consumer market microstructure and verified cross-platform intelligence."""
    panel_anchor = '<section class="panel"><div class="eyebrow">CROSS-PLATFORM CHECK</div>'
    script_anchor = 'async function loadSignals()'
    startup_anchor = 'loadMarket();loadSignals();'
    legacy_cross_platform_call = 'updateQuality();loadCrossPlatform()'
    if panel_anchor not in body or script_anchor not in body or startup_anchor not in body:
        return body
    body = body.replace(panel_anchor, _EXECUTION_PANEL + _TRADE_ACTIVITY_PANEL + _VENUE_CONDITIONS_PANEL + panel_anchor, 1)
    body = body.replace(script_anchor, _EXECUTION_SCRIPT + _TRADE_ACTIVITY_SCRIPT + _VENUE_CONDITIONS_SCRIPT + _CROSS_PLATFORM_V2_SCRIPT + script_anchor, 1)
    body = body.replace(legacy_cross_platform_call, 'updateQuality();loadCrossPlatformV2()', 1)
    body = body.replace(
        startup_anchor,
        'loadMarket();loadExecutionQuality();loadLargeTradeActivity();loadVenueConditions();loadSignals();setInterval(loadExecutionQuality,30000);setInterval(loadLargeTradeActivity,60000);setInterval(loadVenueConditions,30000);',
        1,
    )
    return body
