from __future__ import annotations


_PUSH_PANEL = '''<section class="panel" id="background-push-panel"><h2>Background push</h2><p class="muted">Optional Web Push can deliver the same observable alert transitions after this page is closed. Enabling it requires an explicit browser permission gesture and server VAPID readiness.</p><div class="push-actions"><button class="button" id="enable-background-push" type="button">Enable / sync background push</button><button class="input secondary" id="disable-background-push" type="button">Disable background push</button></div><p id="background-push-status" class="muted">Checking background-push availability…</p><p class="muted">Push subscriptions are first-party preferences. PrediBeacon stores the browser push endpoint and encryption keys required by the Web Push protocol; the management token is returned once and retained only as a SHA-256 hash on the server. Alerts remain informational, not forecasts or trading recommendations.</p></section>'''

_PUSH_STYLE = '''.push-actions{display:flex;gap:.75rem;flex-wrap:wrap}.push-actions>*{min-width:210px}@media(max-width:650px){.push-actions>*{width:100%}}'''

_PUSH_SCRIPT = r'''
const pushManagementKey='predibeacon-push-management',pushStatus=document.querySelector('#background-push-status'),pushEnable=document.querySelector('#enable-background-push'),pushDisable=document.querySelector('#disable-background-push');let pushServerConfig=null;
function pushManagement(){try{return JSON.parse(localStorage.getItem(pushManagementKey)||'null')}catch{return null}}
function base64UrlToUint8Array(value){const padding='='.repeat((4-value.length%4)%4),base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(base64);return Uint8Array.from([...raw].map(ch=>ch.charCodeAt(0)))}
function backgroundPreferences(){const byMarket=new Map();for(const item of list()){if(!item.market_id)continue;const current=byMarket.get(item.market_id)||{market_id:item.market_id,breaking:false,execution:false,large:false,gap:false,evidence:false,closing_hours:null};const threshold=Number(item.threshold);if(Number.isFinite(threshold)&&threshold>=1&&threshold<=99)current.probability_threshold=threshold/100;byMarket.set(item.market_id,current)}for(const item of smartList()){if(!item.market_id)continue;const current=byMarket.get(item.market_id)||{market_id:item.market_id,probability_threshold:null};current.breaking=!!item.enabled?.breaking;current.execution=!!item.enabled?.execution;current.large=!!item.enabled?.large;current.gap=!!item.enabled?.gap;current.evidence=!!item.enabled?.evidence;current.closing_hours=item.enabled?.closing?Number(item.closing_hours||24):null;byMarket.set(item.market_id,current)}return [...byMarket.values()]}
async function loadPushConfig(){try{const response=await fetch('/api/v1/push/config',{cache:'no-store'});pushServerConfig=response.ok?await response.json():null}catch{pushServerConfig=null}if(!pushServerConfig?.enabled||!pushServerConfig.public_key){pushStatus.textContent='Background push is not configured on this PrediBeacon deployment. Local browser alerts remain available.';pushEnable.disabled=true;return}pushEnable.disabled=false;pushStatus.textContent=pushManagement()?'Background push is registered. Use Enable / sync after changing alert preferences.':'Background push is available but not enabled in this browser.'}
async function browserPushSubscription(){if(!('serviceWorker'in navigator)||!('PushManager'in window))throw new Error('Web Push is not supported by this browser.');const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64UrlToUint8Array(pushServerConfig.public_key)});return subscription}
async function enableBackgroundPush(){if(!pushServerConfig?.enabled){pushStatus.textContent='Background push is unavailable.';return}const alerts=backgroundPreferences();if(!alerts.length){pushStatus.textContent='Save at least one probability or smart-signal alert first.';return}if(!('Notification'in window)){pushStatus.textContent='Notifications are not supported by this browser.';return}if(Notification.permission==='default')await Notification.requestPermission();if(Notification.permission!=='granted'){pushStatus.textContent='Notification permission was not granted.';return}pushEnable.disabled=true;try{const subscription=await browserPushSubscription(),serialized=subscription.toJSON(),management=pushManagement();if(management?.subscription_id&&management?.management_token){const response=await fetch('/api/v1/push/subscriptions/'+encodeURIComponent(management.subscription_id)+'/alerts',{method:'PUT',headers:{'Content-Type':'application/json','X-PrediBeacon-Push-Token':management.management_token},body:JSON.stringify({alerts})});if(!response.ok)throw new Error('Unable to synchronize the existing push subscription.');pushStatus.textContent='Background push preferences synchronized.';}else{const response=await fetch('/api/v1/push/subscriptions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({endpoint:serialized.endpoint,keys:{p256dh:serialized.keys?.p256dh,auth:serialized.keys?.auth},alerts})});if(!response.ok)throw new Error('Unable to register background push.');const created=await response.json();localStorage.setItem(pushManagementKey,JSON.stringify({subscription_id:created.subscription_id,management_token:created.management_token}));pushStatus.textContent='Background push enabled for '+created.alert_count+' market preference'+(created.alert_count===1?'':'s')+'.';}}catch(error){pushStatus.textContent=error instanceof Error?error.message:'Background push could not be enabled.'}finally{pushEnable.disabled=!pushServerConfig?.enabled}}
async function disableBackgroundPush(){const management=pushManagement();pushDisable.disabled=true;try{if(management?.subscription_id&&management?.management_token)await fetch('/api/v1/push/subscriptions/'+encodeURIComponent(management.subscription_id),{method:'DELETE',headers:{'X-PrediBeacon-Push-Token':management.management_token}});if('serviceWorker'in navigator){const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager?.getSubscription();if(subscription)await subscription.unsubscribe()}localStorage.removeItem(pushManagementKey);pushStatus.textContent='Background push disabled in this browser.'}catch{pushStatus.textContent='Background push could not be fully disabled. Try again.'}finally{pushDisable.disabled=false}}
pushEnable.addEventListener('click',enableBackgroundPush);pushDisable.addEventListener('click',disableBackgroundPush);document.addEventListener('click',event=>{if(pushManagement()&&(event.target.closest('#add')||event.target.closest('#add-smart')||event.target.closest('.remove')||event.target.closest('.remove-smart')))setTimeout(()=>{pushStatus.textContent='Alert preferences changed. Use Enable / sync background push to update server-side push preferences.'},0)});loadPushConfig();
'''


def enhance_push_alerts_template(body: str) -> str:
    if '</main>' not in body or '</style>' not in body or '</script>' not in body:
        return body
    body = body.replace(
        'Durable background push is not enabled.',
        'Optional background push can be enabled separately when this deployment has Web Push readiness.',
        1,
    )
    body = body.replace('</main>', _PUSH_PANEL + '</main>', 1)
    body = body.replace('</style>', _PUSH_STYLE + '</style>', 1)
    body = body.replace('</script>', _PUSH_SCRIPT + '</script>', 1)
    return body
