from __future__ import annotations

from app.main import app
from app.routes.commercial_intelligence import router as commercial_intelligence_router
from app.routes.contract_verification import router as contract_verification_router
from app.routes.public_contract_verification import router as public_contract_verification_router


app.include_router(commercial_intelligence_router)
app.include_router(contract_verification_router)
app.include_router(public_contract_verification_router)
